-- spellchecker:off
return {
  help_commands = {
    help = true,
    hel = true,
    he = true,
    h = true,
  },
  file_commands = {
    edit = true,
    e = true,
    read = true,
    r = true,
    write = true,
    w = true,
    saveas = true,
    sav = true,
    split = true,
    sp = true,
    vsplit = true,
    vs = true,
    tabedit = true,
    tabe = true,
    badd = true,
    bad = true,
    next = true,
    n = true,
    previous = true,
    prev = true,
    args = true,
    source = true,
    so = true,
    find = true,
    fin = true,
    diffsplit = true,
    diffs = true,
    diffpatch = true,
    diffp = true,
    make = true,
  },
  completion_types = {
    buffer = { 'buffer', 'diff_buffer' },
    path = { 'dir', 'dir_in_path', 'file', 'file_in_path' },
  },
}
-- spellchecker:on
