name: Deploy `main` docs

on:
  push:
    branches:
      - main
    paths:
      - doc/**
      - .github/workflows/docs.yaml

jobs:
  deploy-docs:
    if: github.repository == 'Saghen/blink.cmp'
    name: Deploy docs
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false
          fetch-depth: 0
          fetch-tags: true
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6

      - name: Build
        run: npm ci && npm run build
        working-directory: doc

      - name: Deploy
        uses: cloudflare/wrangler-action@9acf94ace14e7dc412b076f2c5c20b8ce93c79cd # v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy doc/.vitepress/dist --project-name=blink-cmp-main
