name: Test Nix

on:
  push:
    paths:
      - "**/*.lua"
      - "**/*.rs"
      - ".cargo/**"
      - Cargo.lock
      - Cargo.toml
      - Cross.toml
      - rust-toolchain.toml
      - flake.lock
      - flake.nix
      - .github/workflows/nix.yaml
  pull_request:
    paths:
      - "**/*.lua"
      - "**/*.rs"
      - ".cargo/**"
      - Cargo.lock
      - Cargo.toml
      - Cross.toml
      - rust-toolchain.toml
      - flake.lock
      - flake.nix
      - .github/workflows/nix.yaml

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    name: Test Nix Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - uses: DeterminateSystems/nix-installer-action@main

      - name: Check the flake
        run: nix flake check
