name: Stylua

permissions:
  contents: read

on:
  push:
    branches:
      - main
    paths:
      - "**/*.lua"
      - .stylua.toml
      - .github/workflows/stylua.yaml
  pull_request:
    paths:
      - "**/*.lua"
      - .stylua.toml
      - .github/workflows/stylua.yaml

env:
  CLICOLOR: 1

jobs:
  stylua:
    name: Check lua files using Stylua
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v6
        with:
          persist-credentials: false

      - name: Stylua Check Repo
        uses: JohnnyMorganz/stylua-action@76fd70c03e6340ceaf673366712db9b20560b402 # v5.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: --color=always --check .
